### ISSUE TITLE
Error when running ksampler

### ISSUE THREAD

**Issue by formulake** [TheMistoAI/MistoControlNet-Flux-dev#1]
I'm using a conditioning image that's 896x1152 and a GGUF Q8 version of Flux Dev and the ksampler returns this error:
```

Error occurred when executing KSamplerTheMisto:

Error while processing rearrange-reduction pattern "b c (h ph) (w pw) -> b (h w) (c ph pw)".
Input tensor shape: torch.Size([1, 16, 155, 120]). Additional info: {'ph': 2, 'pw': 2}.
Shape mismatch, can't divide axis of length 155 in chunks of 2
```

**Comment by hainguyen666** [comment]
![image](https://github.com/user-attachments/assets/087309e6-a085-4300-8b75-53b24658e444)
I also got ksampler error

**Comment by kiron111** [comment]
Note: The length and width of the conditioning image must be divisible by 16, or an error will occur.

**Comment by kiron111** [comment]
After some trial and error, I found that, even both width and height is divisible by 16, if not square dimentiion, error occurs.
I can't test on the logic of the bug.... (each time of a run, costs me 5 mins)
I just resize to a square dimension (new width = new height = longest side of origina image, with pading of pixels), and finally resize to the original image with crop (i.e get rid of the black padding pixels).
You may use crop and center (but losing some proportion of original image), personally not my choice.
![image](https://github.com/user-attachments/assets/887b41de-3ba7-4cbe-9dc0-96130a9209a5)

**Comment by formulake** [comment]
I did try 1024x1024 but got a different error with that as well. Seems like the current implementation is riddled with problems and isn't performing as expected at the moment. I appreciate all the suggestions and assistance provided here and hope the devs are able to put out a working optimised version because their SDXL controlnet was excellent.

**Comment by baizh0u** [comment]
use git pull to upgrade this repo can fixed this.
