### ISSUE TITLE
 Who knows how to install this?

### ISSUE THREAD

**Issue by abomonov** [TheMistoAI/MistoControlNet-Flux-dev#18]
Warning: Missing Node Types
When loading the graph, the following node types were not found:

LoadTheMistoFluxControlNet
ApplyTheMistoFluxControlNet
KSamplerTheMisto
No selected item
Nodes that have failed to load will show as red on the graph.

**Comment by abomonov** [comment]
![Screenshot_2](https://github.com/user-attachments/assets/9155f232-1e8b-4ed8-bc28-4112bc566409)
![Screenshot_3](https://github.com/user-attachments/assets/b5ef52a4-731a-41ff-9940-5f21b90c420e)
![Screenshot_4](https://github.com/user-attachments/assets/2ed3df6c-c5f5-450b-9b26-8bfed8d2268f)
![Screenshot_5](https://github.com/user-attachments/assets/966453e0-bf2a-49d3-9c40-03090791b2f0)
I have everything installed and still no nodes. Is this a bug?

**Comment by baizh0u** [comment]
Try to use the new example workflow file.

**Comment by abomonov** [comment]
> Try to use the new example workflow file.

I used it. Does it work for you?

**Comment by Meathelix1** [comment]
I also have the same issue as you.

**Comment by baizh0u** [comment]
can you also upload the terminal screenshot as well?

**Comment by abomonov** [comment]
> can you also upload the terminal screenshot as well?

![Screenshot_2](https://github.com/user-attachments/assets/c7b1f684-75f8-4b9f-b527-29efa2dc0779)

**Comment by baizh0u** [comment]
you need to pip install diffusers..

**Comment by abomonov** [comment]
> you need to pip install diffusers..

I installed diffusers and now everything works, thanks!
