### ISSUE TITLE
Very slow, over 100s/it on 12gb Vram

### ISSUE THREAD

**Issue by Malergh-M** [TheMistoAI/MistoControlNet-Flux-dev#2]
I have a 2080ti with 12gb vram and i get 137s/it. 
Im using gguf q4_k_m, and gguf dual clip loader with T5 encoder Q8.

That is on 1024x1024

I changed it down to 720x720 and now it is 12s/it

**Comment by baizh0u** [comment]
try the new example_workflow by git pull to upgrade this repo
