### ISSUE TITLE
AnyLine预处理器 

### ISSUE THREAD

**Issue by nno-magic** [TheMistoAI/MistoControlNet-Flux-dev#20]
An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
错误报告：
# ComfyUI Error Report
## Error Details
- **Node Type:** AnyLineArtPreprocessor_aux
- **Exception Type:** huggingface_hub.utils._errors.LocalEntryNotFoundError
- **Exception Message:** An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
## Stack Trace
```
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

**Comment by nno-magic** [comment]
![Uploading 微信图片_20240904093747.png…]()

**Comment by baizh0u** [comment]
如果你是在中国大陆地区，第一次使用Anyline的时候要全局，它有个很小的模型要下载。

**Comment by nno-magic** [comment]
> 如果你在中国大陆地区，第一次使用Anyline的时候要全局，有一个很小的模型要下载。

所以是我没有挂vpn才出现模型没有下载的情况吗，懂了，多谢

**Comment by nno-magic** [comment]
> 如果你在中国大陆地区，第一次使用Anyline的时候要全局，有一个很小的模型要下载。

 我刚下载了Anyline，可以使用，但是misto的FLUX这个预处理器节点还是报错
![Uploading 微信图片_20240904171750.png…]()

**Comment by baizh0u** [comment]
你的图挂了

**Comment by nno-magic** [comment]
> 你的图挂了
你说的那个模型应该是MTEED.pth，我去网上单独下了那个文件，还是提示错误

**Comment by nno-magic** [comment]
> 你的图挂了

明白问题出现在哪了，他官方的工作流用的是之前xl的预处理器，去他flux插件里找他自己的预处理器换上就能用了
