### ISSUE TITLE
用给的官方工作流运行报错

### ISSUE THREAD

**Issue by DanielYuan1993** [TheMistoAI/MistoControlNet-Flux-dev#3]
Error occurred when executing KSamplerTheMisto:

The size of tensor a (5100) must match the size of tensor b (5160) at non-singleton dimension 1

![6529925274e39109c2e845e74ff8682](https://github.com/user-attachments/assets/44b9b76f-b7e1-4377-9463-9edae865cf41)

**Comment by baizh0u** [comment]
use git pull to upgrade this repo can fixed this. and use the new example_workflow
