### ISSUE TITLE
Awful Results

### ISSUE THREAD

**Issue by inferno46n2** [TheMistoAI/MistoControlNet-Flux-dev#5]
When I run this in ComfyUI I get NO WHERE NEAR the results displayed on your page.

Please confirm what the requirements are? Image left source, image right (dark) the output from using this CN

![image](https://github.com/user-attachments/assets/ffab3e18-a845-4d68-ba14-4606d47b434c)

**Comment by baizh0u** [comment]
for this case you need to use a preprocessor to get a lineart or scrible image first. Direct using photo is not fit for this cn.

**Comment by vlrevolution** [comment]
Why preprocessor is used in these images? Anyline?
![image](https://github.com/user-attachments/assets/e8cbc98c-2c06-4965-82a4-742f89bd844c)

**Comment by vlrevolution** [comment]
Do you have a proper workflow file you could attach, please? :)

**Comment by baizh0u** [comment]
Checkout the workflow folder from our repo. We upload a example workflow there.vlrevolution ***@***.***>於2024年8月31日 17:54寫道：﻿
Do you have a proper workflow file you could attach, please? :)

**Comment by vlrevolution** [comment]
I see! Btw why do you use 960 resolution? If I use 1024, it is no problem or best to stick to 960 for some reason?

**Comment by baizh0u** [comment]
No just for accurate my test process…. 1024 is too slow even for us…vlrevolution ***@***.***>於2024年8月31日 18:13寫道：﻿
I see, thank you, trying now! Btw why do you use 960 resolution? If I use 1024, it is no problem or best to stick to 960 for some reason?

**Comment by vlrevolution** [comment]
What resolution was controlnet trained on ?

**Comment by vlrevolution** [comment]
Any tips to get better lineart from images that are somewhat abstract in shapes? It is not working well for cat images
![image](https://github.com/user-attachments/assets/0db6f440-587f-480a-a4a9-b6ca7df2f534)

**Comment by baizh0u** [comment]
maybe try TEED or canny?

**Comment by inferno46n2** [comment]
> for this case you need to use a preprocessor to get a lineart or scrible image first. Direct using photo is not fit for this cn.

I obviously used a lineart preprocessor first haha
