### ISSUE TITLE
2080ti魔改22G，报错，求解

### ISSUE THREAD

**Issue by zhai-hello** [TheMistoAI/MistoControlNet-Flux-dev#6]
![Snipaste_2024-08-31_09-01-24](https://github.com/user-attachments/assets/0663f388-7a57-4bfe-aab6-131c35837a51)
Error occurred when executing KSamplerTheMisto:

No operator found for `memory_efficient_attention_forward` with inputs:
query : shape=(24, 4352, 1, 128) (torch.bfloat16)
key : shape=(24, 4352, 1, 128) (torch.bfloat16)
value : shape=(24, 4352, 1, 128) (torch.bfloat16)
attn_bias :
p : 0.0
`decoderF` is not supported because:
attn_bias type is
bf16 is only supported on A100+ GPUs
`flshattF@v2.5.7` is not supported because:
requires device with capability > (8, 0) but your GPU has capability (7, 5) (too old)
bf16 is only supported on A100+ GPUs
`cutlassF` is not supported because:
bf16 is only supported on A100+ GPUs
`smallkF` is not supported because:
max(query.shape[-1] != value.shape[-1]) > 32
dtype=torch.bfloat16 (supported: {torch.float32})
bf16 is only supported on A100+ GPUs
unsupported embed per head: 128

**Comment by baizh0u** [comment]
更新插件，可能会修复问题，但是你这个魔改的显卡未必能跑。

**Comment by zhai-hello** [comment]
从别处看到的解决方法，试了一下，果然可以了。[MistoControlNet-Flux-dev]这个效果很不错，大家都给作者点star
具体方式是：我用的秋叶启动包，点击左侧高级选项，然后cross-attention 优化方案修改成使用缩放积点SDP方案，就可以了。
![Uploading Snipaste_2024-08-31_18-14-03.jpg…]()
