### ISSUE TITLE
Very slow and show ERROR lora diffusion_model.single_blocks.36.linear2.weight Allocation on device

### ISSUE THREAD

**Issue by xueqing0622** [TheMistoAI/MistoControlNet-Flux-dev#9]
Very slow and show ERROR lora diffusion_model.single_blocks.36.linear2.weight Allocation on device
3060 12G
Sampling:  25%|██████████████████▌                                                       | 2/8 [00:39<01:52, 18.75s/it]ERROR lora diffusion_model.single_blocks.37.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.0.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.1.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.3.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.5.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.6.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.7.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.9.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.10.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.11.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.13.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.17.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.20.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.21.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.22.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.25.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.28.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.29.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.31.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.33.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.34.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.36.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.37.linear2.weight Allocation on device
Sampling:  38%|███████████████████████████▊                                              | 3/8 [00:56<01:30, 18.11s/it]ERROR lora diffusion_model.single_blocks.28.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.36.linear2.weight Allocation on device
Sampling:  50%|█████████████████████████████████████                                     | 4/8 [01:10<01:05, 16.42s/it]ERROR lora diffusion_model.single_blocks.6.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.9.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.10.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.13.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.22.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.26.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.27.linear2.weight Allocation on device
Sampling:  62%|██████████████████████████████████████████████▎                           | 5/8 [01:28<00:51, 17.01s/it]ERROR lora diffusion_model.single_blocks.0.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.2.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.18.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.21.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.22.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.26.linear2.weight Allocation on device

**Comment by baizh0u** [comment]
maybe for 3060 you need parallel loading for flux.dev model
